#!/bin/sh

SHARED_BOOT_FOLDER="$HOME/vmshare/boot"
KERNEL_VERSION="5.4.0-rc3+"
COMPRESSED_IMAGE=vmlinuz-$KERNEL_VERSION
CONFIG_FILE=config-$KERNEL_VERSION
SYSTEM_MAP=System.map-$KERNEL_VERSION

cp $SHARED_BOOT_FOLDER/$COMPRESSED_IMAGE /boot/$COMPRESSED_IMAGE
cp $SHARED_BOOT_FOLDER/$CONFIG_FILE /boot/$CONFIG_FILE
cp $SHARED_BOOT_FOLDER/$SYSTEM_MAP /boot/$SYSTEM_MAP

update-grub